#define     bag_enum_base                0x10177BC        //
#define     bag_enum_offset1              0x34        //
#define     bag_enum_offset2              0x80        //
#define     bag_enum_offset3              0x7A8        //
#define     bag_grid_nums_base           0x10177BC        //
#define     bag_grid_nums_offset1         0x34        //
#define     bag_grid_nums_offset2         0x80        //
#define     bag_grid_nums_offset3         0x188        //
#define     bag_item_type_offset             0x8        //
#define     bag_item_id_offset1           0xC        //
#define     bag_item_id_offset2           0x8        //
#define     bag_item_nameid_offset1         0xC        //
#define     bag_item_nameid_offset2         0x6E8        //
#define     bag_item_name_call_base          0x1018C20        //
#define     bag_item_name_call_offset1            0x2938        //
#define     bag_item_name_call_offset2            0x48        //
#define     bag_item_pos_offset             0x1E        //
#define     bag_item_nums_offset             0x2E        //
#define     bag_item_durability_offset               0x48        //
#define     bag_item_level_offset1           0xC        //
#define     bag_item_level_offset2           0x78        //
#define     yao_cd_base               0x1018C20        //
#define     yao_cd_offset1             0x1E40        //
#define     yao_cd_offset2             0x48        //
#define     yao_cd_offset3             0xC        //
#define     yao_cd_offset4             0x854        //
#define     yao_cd_offset5             0x850        //
#define     yao_cd_offset6             0x34        //
#define     yao_cd_offset7             0x80        //
#define     yao_cd_offset8             0x724        //
#define     yao_cd_offset9             0x34        //
#define     yao_cd_offset10             0x80        //
#define     yao_cd_call             0x4D3020        //
#define     item_bag_type_offset             0x1C        //
#define     bag_item_color_offset1             0xC        //
#define     bag_item_color_offset2             0x82        //
#define     rbt_type_call            0x6EBB20        //
#define     bag_item_bidui_offset1            0xC        //
#define     bag_item_bidui_offset2            0xC        //
#define     bag_item_bidui1_offset1           0xC        //
#define     bag_item_bidui1_offset2           0x5DD        //
#define     wuqi_xp_all1_offset1      0xC        //
#define     wuqi_xp_all1_offset2      0xC        //
#define     wuqi_xp_all1_offset3      0xC        //
#define     wuqi_xp_all1_offset4      0x5D8        //
#define     wuqi_xp_all1_offset5      0x1348        //
#define     wuqi_xp_all1_offset6      0x48        //
#define     wuqi_xp_all2_offset1      0xC        //
#define     wuqi_xp_all2_offset2      0xC        //
#define     wuqi_xp_all2_offset3      0xC        //
#define     wuqi_xp_all2_offset4      0x5D8        //
#define     wuqi_xp_all2_offset5      0x1348        //
#define     wuqi_xp_all2_offset6      0x48        //
#define     wuqi_xp_cur_offset             0x28        //
#define     wuqi_pj_offset              0x24        //
#define     bag_item_bagua_pos_offset1           0xC        //
#define     bag_item_bagua_pos_offset2           0x26        //
#define     bag_newslot_call              0x6DE840        //
#define     bag_newslot_offset1              0x40        //
#define     bag_newslot_offset2              0x58        //
#define     bag_newslot_offset3              0x5B        //
#define     bag_newslot_offset4              0xC        //
#define     bag_refresh_c5            0x1BD0        //
#define     bag_cuncang_call               0x6D7B20        //
#define     bag_delete_call              0x47DCD0        //
#define     bag_delete_offset1              0x34        //
#define     bag_delete_offset2              0x80        //
#define     bag_delete_offset3              0x7A8        //
#define     jiefeng_call              0x47F080        //
#define     jiefeng_offset1              0x34        //
#define     jiefeng_offset2              0x80        //
#define     jiefeng_offset3              0x7A8        //
#define     jiefeng_hezi_call              0x47E0D0        //
#define     jiefeng_hezi_offset1              0x34        //
#define     jiefeng_hezi_offset2              0x80        //
#define     jiefeng_hezi_offset3              0x7A8        //
#define     sell_call               0x894A70        //
#define     fenjie_call              0x47E0D0        //
#define     fenjie_offset1              0x34        //
#define     fenjie_offset2              0x80        //
#define     fenjie_offset3              0x7A8        //
#define     open_npc_call             0x433B80        //
#define     open_npc_offset1             0x34        //
#define     open_npc_offset2             0x80        //
#define     open_npc_offset3             0x724        //
#define     close_npc_c5           0x40        //
#define     buy_call              0x893D20        //手动找一下无法定位
#define     chiyao_call                0x47CA70        //
#define     chiyao_offset1                0x34        //
#define     chiyao_offset2                0x80        //
#define     chiyao_offset3                0x7A8        //
#define     pickup1_call              0x433B80        //
#define     pickup2_call              0x427E10        //
#define     pickup1_offset1              0x34        //
#define     pickup1_offset2              0x80        //
#define     pickup1_offset3              0x724        //
#define     pickup2_offset1              0x34        //
#define     pickup2_offset2              0x80        //
#define     pickup2_offset3              0x724        //
#define     jiabaoshi_call               0x47DE90        //
#define     jiabaoshi_offset1               0x34        //
#define     jiabaoshi_offset2               0x80        //
#define     jiabaoshi_offset3               0x7A8        //
#define     xiebaoshi_call               0x47DFB0        //
#define     xiebaoshi_offset1               0x34        //
#define     xiebaoshi_offset2               0x80        //
#define     xiebaoshi_offset3               0x7A8        //
#define     chuanzhuangbei_call               0x428BF0        //
#define     chuanzhuangbei_offset3               0xF8        //
#define     xiezhuangbei_call               0x47B900        //
#define     xiezhuangbei_offset1               0x34        //
#define     xiezhuangbei_offset2               0x80        //
#define     xiezhuangbei_offset3               0x7A8        //
#define     kaihezi_call               0x47E0D0        //
#define     kaihezi_offset1               0x34        //
#define     kaihezi_offset2               0x80        //
#define     kaihezi_offset3               0x7A8        //
#define     hewuqi_call              0x481620        //
#define     hewuqi_offset1              0x34        //
#define     hewuqi_offset2              0x80        //
#define     hewuqi_offset3              0x7A8        //
#define     hewuqi_po5_call            0x481F10        //
#define     hewuqi_po5_offset1            0x34        //
#define     hewuqi_po5_offset2            0x80        //
#define     hewuqi_po5_offset3            0x7A8        //
#define     hewuqi_po10_call           0x47FF00        //
#define     hewuqi_po10_offset1           0x34        //
#define     hewuqi_po10_offset2           0x80        //
#define     hewuqi_po10_offset3           0x7A8        //
#define     ui_enum_base                0x10177BC        //
#define     ui_enum_offset1              0x2C        //
#define     ui_enum_offset2              0x4        //这个偏移+4才是真的偏移
#define     ui_enum_offset3              0x4        //这个偏移+4才是真的偏移
#define     ui_enum_offset4              0x4        //
#define     obj_enum_base               0x10177BC        //
#define     obj_enum_offset1             0x34        //
#define     obj_enum_offset2             0x9C        //这个偏移+4才是真的二级偏移
#define     obj_enum_offset3             0x4        //
#define     obj_type_offset                0xE        //
#define     obj_name_call_base           0x1018C20        //
#define     obj_name_call_offset1         0x2938        //
#define     obj_name_call_offset2         0x48        //
#define     obj_type4_id_offset              0x8        //
#define     obj_type4_id2_offset             0xC        //
#define     obj_type4_view_offset1         0x14        //
#define     obj_type4_view_offset2         0x3CF8        //
#define     obj_type4_name_offset1        0x728        //
#define     obj_type4_mapid          0x90        //
#define     obj_type4_health              0xC0        //
#define     player_pos_x_offset1          0x14        //
#define     player_pos_x_offset2          0x3CEC        //
#define     player_pos_y_offset2          0x3CEC        //X坐标+4的偏移
#define     player_pos_z_offset2          0x3CEC        //X坐标+8的偏移
#define     obj_type4_pos2_x_offset           0x94        //
#define     obj_type4_pos2_y_offset           0x94        //X坐标+2
#define     obj_type4_pos2_z_offset           0x94        //X坐标+4
#define     ojb_type20_nameid_offset1       0xC0        //
#define     ojb_typeb0_mapid_offset         0x24        //
#define     ojb_typeb0_pos2_x            0x28        //
#define     ojb_typeb0_pos2_y            0x28        //X坐标+2
#define     ojb_typeb0_pos2_z            0x28        //X坐标+4
#define     ojb_type4_pos2_x            0xE8        //可以用这个偏移 也可以用这个减去0x10的偏移
#define     obj_type4_youshan_offset1          0x728        //这个我就直接写偏移123了 到代码中去比对吧
#define     obj_type4_youshan_offset2          0x3F        //这个我就直接写偏移123了 到代码中去比对吧
#define     obj_type4_youshan_offset3          0x3E        //这个我就直接写偏移123了 到代码中去比对吧
#define     obj_type4_youshan_offset4          0x20B        //这个我就直接写偏移123了 到代码中去比对吧
#define     obj_type4_pos_x_offset1         0x14        //
#define     obj_type4_pos_x_offset2         0x1A8        //
#define     is_login_readme_offset     0x38        //
#define     login_call_c5_offset        0x48        //
#define     is_logingame_base      0x10177BC        //
#define     is_logingame_offset1    0x2C        //
#define     is_logingame_offset2    0xC        //
#define     is_logingame_offset3    0x4        //
#define     account_info_base               0x10177BC        //没用上
#define     account_info_offset1             0xFFFFFF        //没用上
#define     account_info_offset2             0xC        //2个二级偏移相加才是真的二级偏移
#define     account_info_offset21            0x4        //2个二级偏移相加才是真的二级偏移
#define     account_info_class_offset             0x2        //没用上
#define     select_character_offset  0x200        //
#define     login_call              0x8B5C70        //
#define     move_status_base                0x10177BC        //
#define     move_status_offset1              0x2C        //
#define     move_status_offset2              0x1C        //
#define     move_status_offset3              0x45008        // move_status_offset3需要这2个相加才是真正的三级偏移
#define     move_status_offset31             0x21B        // 动画状态三级偏移需要这2个相加才是真正的三级偏移
#define     get_jiangli_call              0x523D50        //
#define     get_jiangli_base                0x10177BC        //
#define     get_jiangli_offset1              0x34        //
#define     get_jiangli_offset2              0x80        //
#define     get_jiangli_offset3              0x7EC        //
#define     get_jiangli_offset4              0x1ED0        //
#define     yaojiang_confrim_c5            0x1ED0        //回头再找
#define     yaojiang_isshow_c5           0x3C        //
#define     yaojiang_close_c5         0x3C        //回头再找
#define     yaojiang_close_isshow_offset      0x4C        //
#define     yaojiang_close_confrim_c5     0x1C8        //
#define     mouse_mode_isclass_base          0x1051774        //
#define     mouse_mode_class_c5           0x3BC1C        //
#define     mouse_mode_class_offset1              0x3B9FC        //这两个一级偏移相加才是真的一级偏移
#define     mouse_mode_class_offset11             0x8        //这两个一级偏移相加才是真的一级偏移
#define     mouse_mode_class_offset2              0x20        //
#define     post_xianlu_c5        0x58        //
#define     post_xianlu_offset1          0x2C        //
#define     post_xianlu_offset2          0x4        //这个偏移再 +4 才是真的偏移
#define     xianlu_count_offset1         0x7C        //
#define     xianlu_count_array_size         0x10        //
#define     huanxian_call                0x4D6370        //
#define     player_xianlu_base             0x10177BC        //
#define     player_xianlu_offset1           0x34        //
#define     player_xianlu_offset2           0x80        //
#define     player_xianlu_offset3           0x764        //
#define     step_call_base              0x1017788        //
#define     step_call_offset1            0x138        //
#define     mail_call                0x43CAC0        //
#define     mail_call_offset1                0x2C        //
#define     mail_call_offset2                0x1C        //
#define     mail_call_offset3                0x44FBC        //
#define     mail_call_offset4                0x44FB8        //
#define     mail_call_offset5                0x34        //
#define     mail_call_offset6                0x80        //
#define     mail_call_offset7                0x818        //
#define     nums_strike_strcut_offset      0x40        //
#define     nums_strike_strcut_size           0x3D8        //
#define     nums_strike_strcut_id           0x20        //
#define     nums_strike_canuse         0x30        //技能是否可以使用的偏移  这个偏移再+0x10  才是真正的偏移
#define     nums_strike_islock           0x34        //技能是否可以使用的偏移  这个偏移再+0x10  才是真正的偏移
#define     nums_strike_id2          0x24        //
#define     nums_strike_cd                0xC0        //这个偏移再+0x10  才是真正的偏移
#define     nums_strike_call_base            0x1018C20        //
#define     nums_strike_call_offset1          0x1E40        //
#define     nums_strike_call_offset2          0x48        //
#define     nums_strike_call            0xA62350        //
#define     letter_strike_start_offset2        0x24        //
#define     letter_strike_start_offset3        0x68        //
#define     letter_strike_id              0xB88        //
#define     letter_strike_i2             0xB88        //这个偏移+4才是ID2的偏移
#define     letter_strike_islock           0x34        //这个偏移减去0x10才是真正的偏移
#define     letter_strike_canuse         0x30        //这个偏移减去0x10才是真正的偏移
#define     letter_strike_cd             0xC0        //这个偏移减去0x10才是真正的偏移
#define     add_strike_call              0x516C80        //
#define     add_strike_call_base           0x10177BC        //
#define     add_strike_offset1          0x34        //
#define     add_strike_offset2          0x80        //
#define     add_strike_offset3          0x7B0        //
#define     confrim_call             0x517E20        //
#define     confrim_call_base          0x10177BC        //
#define     confrim_add_strike_offset1         0x34        //
#define     confrim_add_strike_offset2         0x80        //
#define     confrim_add_strike_offset3         0x7B0        //
#define     delete_strike_call             0x5172C0        //
#define     delete_strike_call_base          0x10177BC        //
#define     delete_strike_call_offset1         0x34        //
#define     delete_strike_call_offset2         0x80        //
#define     delete_strike_call_offset3         0x7B0        //
#define     attack_call              0x42D940        //
#define     attack_offset1              0x34        //
#define     attack_offset2              0x80        //
#define     attack_offset3              0x724        //
#define     skillpanel_isshow  0x38        //
#define     open_clearstrike_offset           0x58        //
#define     clearstrike_isopen         0x58        //
#define     confrim_clearallstrike           0x70        //
#define     player_base                  0x10177BC        //
#define     player_offset1                0x34        //
#define     player_offset2                0x80        //
#define     player_pos2_x             0x94        //
#define     player_pos2_y             0x94        //X坐标+2
#define     player_pos2_z             0x94        //X坐标+4
#define     player_steppos_x_offset1           0x14        //
#define     player_steppos_x_offset2           0x3CEC        //
#define     player_steppos_y_offset2           0x3CEC        //X坐标+4
#define     player_steppos_z_offset2           0x3CEC        //X坐标+8
#define     player_cur_health             0xC0        //
#define     player_max_health               0x214        //
#define     player_bagua_health             0x218        //
#define     player_cur_level             0x9C        //
#define     player_mapid           0x90        //
#define     player_id1               0x8        //
#define     player_id2              0xC        //
#define     player_name_neigong_offset             0xF4        //
#define     player_name_qinggong_offset1           0x14        //
#define     player_name_qinggong_offset2           0x23C        //这个数值+4 是角色最大轻功 代码中用的这个偏移
#define     player_name_offset               0x8C        //
#define     player_status_ispickupbody_offset3            0x158        //现在用的是这个偏移
#define     player_status_attack_offset           0x208        //
#define     player_status_step_offset1          0x14        //
#define     player_status_step_offset2          0x1EC        //
#define     player_status_down           0x148        //
#define     player_status_openblock             0x110        //5代表在开锁，拿物品的状态中   2表示可以二次捡物了
#define     dundi_call                0x429900        //
#define     dundi_offset1                0x34        //
#define     dundi_offset2                0x80        //
#define     dundi_offset3                0x724        //
#define     dundi_chuning_status_offset4            0x170        //
#define     pickup_body_call              0x4288E0        //
#define     pickup_body_offset1              0x34        //
#define     pickup_body_offset2              0x80        //
#define     pickup_body_offset3              0x724        //
#define     pickdown_body_call              0x6AB360        //
#define     pickdown_body_offset1              0x2C        //
#define     pickdown_body_offset2              0xC        //
#define     pickdown_body_offset3              0x452A8        //
#define     pickdown_body_offset4              0x302D0        //
#define     pickdown_body_offset5              0x3        //
#define     player_ispickup_deadbody_offset3         0x158        //
#define     fuhuo_call                0x6AB360        //
#define     fuhuo_offset1                0x44        //
#define     player_dead_status_offset3            0x1C0        //
#define     huohua_offset1              0x34        //
#define     huohua_offset2              0x80        //
#define     huohua_offset3              0x724        //
#define     huohua_offset4              0x218        //
#define     huohua_offset5              0x21C        //
#define     huohua_call              0x433B80        //
#define     step_back_offset1              0x2C        //
#define     step_back_offset2              0xC        //
#define     step_back_offset3              0x452A8        //
#define     step_back_offset4              0x302D0        //
#define     step_back_offset5              0x2BF8        //
#define     deliver_quest_call               0x4EE5B0        //
#define     deliver_quest_offset1               0x34        //
#define     deliver_quest_offset2               0x80        //
#define     deliver_quest_offset3               0x7AC        //
#define     npc_quest_call            0x4ED5C0        //
#define     npc_quest_offset1            0x34        //
#define     npc_quest_offset2            0x80        //
#define     npc_quest_offset3            0x7AC        //
#define     npc_quest_offset4            0xC        //原先的
#define     npc_quest_offset5            0x8        //原先的
#define     shunyi_call                0x5BD2C0        //
#define     shunyi_offset1                0x0        //
#define     shunyi_offset2                0x0        //
#define     shunyi_offset3                0x34        //
#define     shunyi_offset4                0x80        //
#define     shunyi_offset5                0x14        //
#define     shunyi_offset6                0x298        //
#define     shunyi_offset7                0x39DA        //
#define     npc_duihuakuang_isopen_offset       0x38        //
#define     over_shunyi_call              0x5BC6F0        //
#define     over_shunyi_call_offset1          0x34        //
#define     over_shunyi_call_offset2          0x80        //
#define     over_shunyi_call_offset3          0x14        //
#define     over_shunyi_call_offset4          0x298        //
#define     hook_dont_leave_dungeons            0x5BC500        //
#define     hook_dont_leave_dungeons_beitai   0x5BC500        // 这个是备用的 万一上面的特征码失效就用这个特征码
#define     hook_combat_call            0x438AE7        //
#define     invite_party_call              0x4ABDB0        //
#define     invite_party_call_offset1          0x34        //
#define     invite_party_call_offset2          0x80        //
#define     invite_party_call_offset3          0x7BC        //
#define     invite_ui_isopen_offset        0x38        //
#define     invite_ui_click_c5            0x44        //
#define     leave_party_call             0x4ACB00        //
#define     enum_party_startaddr_offset1         0x34        //
#define     enum_party_startaddr_offset2         0x80        //
#define     enum_party_startaddr_offset3         0x7BC        //
#define     enum_party_startaddr_offset4         0x14        //
#define     enum_party_startaddr_offset5         0x14        //这个值再加4才是真正的值
#define     party_obj_id_offset            0x8        //
#define     party_obj_lv_offset            0xA        //这个偏移再加0x10才是真正的偏移
#define     party_obj_sv_offset            0x28        //
#define     Play_fighting_status_offset3           0x208        //
#define     Wuqi_po10_offset1  0x1418        //
#define     Wuqi_po10_offset2  0x18        //
#define     Wuqi_po10_cmp2_offset  0x1A4        //
#define     Wuqi_po10_cmp4_offset  0x28        //
#define     Wuqi_po10_cmp0_offset  0x30        //
#define     Iscs_po10_cmp_offset1           0x24        //
#define     Iscs_po10_cmp_offset2           0x20        //
#define     Iscs_po10_cmp_Call           0x49A950        //
#define     Pickup2_call_ts            0x4278B0        //
#define     Experience_status_offset1             0x83F8        //
#define     Experience_status_offset2             0x9BC        //
#define     Experience_status_offset3             0xC0        //
#define     Experience_status_offset4             0x1C        //
#define     viewpoint_call                 0xAB316C8        //viewpoint_call - bsengine  基础地址 = 差值
#define     viewpoint_offset1               0x3BC        //
#define     viewpoint_offset3               0x40        //
#define     viewpoint_offset4               0x214        //
#define     viewpoint_offset5               0x64        //
#define     x3step_offset1             0x3BC        //
#define     x3step_offset3             0x40        //
#define     x3step_offset4             0x214        //
#define     x3step_offset5             0x2C0        //
#define     tiaoyue_offset1               0x3BC        //
#define     tiaoyue_offset3               0x40        //
#define     tiaoyue_offset4               0x214        //
#define     sxbb_call_offset1          0x3BC        //
#define     sxbb_call_offset2          0x0        //
#define     sxbb_call_offset3          0x40        //
#define     sxbb_call_offset4          0x3A0        //
#define     sxbb_call_offset5          0x41C        //
#define     quest_base                0x10177BC        //
#define     quest_offset1              0x34        //
#define     quest_offset2              0x80        //
#define     quest_offset3              0x7AC        //
#define     quest_offset4              0x8        //
#define     quest_struct_size              0x58        //
#define     quest_id_offset3             0x8        //
#define     quest_nameid_offset3           0x18        //
#define     quest_name_call_base           0x1018C20        //
#define     quest_name_call_offset1         0x2938        //
#define     quest_name_call_offset2         0x48        //